name: React CI

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
    
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: npm install
        working-directory: ./frontend
      - name: build frontend
        run: npm run build
        working-directory: ./frontend
      - run: npm test
        working-directory: ./frontend
      